"""Add cover for playlists

Revision ID: 14cb59464ba7
Revises: 662a2ebc5e52
Create Date: 2023-11-02 14:04:28.601312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cb59464ba7'
down_revision: Union[str, None] = '662a2ebc5e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('cover', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'cover')
    # ### end Alembic commands ###
