"""Add autoincrement

Revision ID: 1ac40f81851b
Revises: ef4af631a51c
Create Date: 2023-11-02 11:16:29.638602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac40f81851b'
down_revision: Union[str, None] = 'ef4af631a51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'albom', ['id'])
    op.create_unique_constraint(None, 'author', ['id'])
    op.create_unique_constraint(None, 'playlist', ['id'])
    op.create_unique_constraint(None, 'song', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'song', type_='unique')
    op.drop_constraint(None, 'playlist', type_='unique')
    op.drop_constraint(None, 'author', type_='unique')
    op.drop_constraint(None, 'albom', type_='unique')
    # ### end Alembic commands ###
