"""Add modify

Revision ID: 2b276cac8648
Revises: 1ac40f81851b
Create Date: 2023-11-02 12:44:55.224508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b276cac8648'
down_revision: Union[str, None] = '1ac40f81851b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playlist_name_key', 'playlist', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('playlist_name_key', 'playlist', ['name'])
    # ### end Alembic commands ###
