"""make song favorite

Revision ID: 320a99af04f4
Revises: 39c4455df05f
Create Date: 2023-12-06 21:55:44.311591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320a99af04f4'
down_revision: Union[str, None] = '39c4455df05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('is_liked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'is_liked')
    # ### end Alembic commands ###
