"""Uniqie false for song name

Revision ID: 39c4455df05f
Revises: ffa7034207f2
Create Date: 2023-11-29 12:20:11.705355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c4455df05f'
down_revision: Union[str, None] = 'ffa7034207f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('song_name_key', 'song', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('song_name_key', 'song', ['name'])
    # ### end Alembic commands ###
