"""delete unique for user_id

Revision ID: 94824cd7bac1
Revises: cd12ce9926b6
Create Date: 2023-11-03 13:01:51.806900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94824cd7bac1'
down_revision: Union[str, None] = 'cd12ce9926b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playlist_username_id_key', 'playlist', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('playlist_username_id_key', 'playlist', ['username_id'])
    # ### end Alembic commands ###
