"""Mod Song

Revision ID: ae58f1f47c98
Revises: 9178959d5228
Create Date: 2023-11-25 10:01:00.033018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae58f1f47c98'
down_revision: Union[str, None] = '9178959d5228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('song_path', sa.String(), nullable=False))
    op.alter_column('song', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('song', 'albom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('song', 'duration_song',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song', 'duration_song',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('song', 'albom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('song', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('song', 'song_path')
    # ### end Alembic commands ###
